package rules;
import com.paper.ssm.core.model.data.Data
import com.paper.ssm.core.model.normalize.Rule
import com.paper.ssm.core.model.normalize.RuleMacro
import com.paper.ssm.core.model.normalize.Attribute
dialect  "mvel"

global Data data;
//
//rule "dataType_int=>double"
//    activation-group "dataType"
//    when
//        $attribute: Attribute(ruleId == RuleMacro.DATATYPE && value == "double")
//        $field: Attribute(value == "int") from $attribute.field
//    then
//        Double value = Double.parseDouble(data.getValue());
//        data.setValue(value.toString());
//        $field.setValue("double");
//end
//
//rule "dataType_double=>int"
//    activation-group "dataType"
//    when
//        $attribute: Attribute(ruleId == RuleMacro.DATATYPE && value == "int")
//        $field: Attribute(value == "double") from $attribute.field
//    then
//        Integer value = Integer.parseInt(data.getValue());
//        data.setValue(value.toString());
//        $field.setValue("int");
//end
//
//
//rule "dataType_int=>boolean"
//    activation-group "dataType"
//    when
//        $attribute: Attribute(ruleId == RuleMacro.DATATYPE && value == "boolean")
//        $field: Attribute(value == "int") from $attribute.field
//    then
//        Boolean value = Boolean.parseBoolean(data.getValue());
//        data.setValue(value.toString());
//        $field.setValue("boolean");
//end
//
//rule "dataType_boolean=>int"
//    activation-group "dataType"
//    when
//        $attribute: Attribute(ruleId == RuleMacro.DATATYPE && value == "int")
//        $field: Attribute(value == "boolean") from $attribute.field
//    then
//        Integer value = Integer.parseInt(data.getValue());
//        data.setValue(value.toString());
//        $field.setValue("int");
//end