package rules;
import com.paper.ssm.run.data.Data
import com.paper.ssm.model.normalize.Rule
import com.paper.ssm.model.normalize.Attribute
import com.paper.ssm.model.normalize.RuleMacro

//dialect  "mvel"

global Data data;

rule  "test"
    when
        eval(true)
    then
        System.out.println("drools is running");
end


rule "label(field == null)"
    when
        $attribute: Attribute()
        $rule: Rule(type == Rule.LABEL_TYPE) from $attribute.getRule()
    then
        data.getFieldList().add($attribute);
end


